### ISSUE TITLE
Cannot use a callback defined in a struct in Queue.SetCallback()

### ISSUE THREAD

**Issue by lstep** [Thermi/nfqueue-go#1]
With a regular func (not in a struct), it works fine. With a func defined in a struct, I get :
```
panic: runtime error: cgo argument has Go pointer to Go pointer
```

**Comment by Thermi** [comment]
That's a cgo limitation. I ran into that myself and I can't fix that _at all_. It's built into go, tha language itself.

Am July 16, 2018 6:25:46 AM UTC schrieb Luc Stepniewski <notifications@github.com>:
>With a regular func (not in a struct), it works fine. With a func
>defined in a struct, I get :
>```
>panic: runtime error: cgo argument has Go pointer to Go pointer
>```
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Thermi/nfqueue-go/issues/1

-- 
Sent from mobile
